# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spt的博客
email: 873640736@qq.com
description:  本人是一个大四即将毕业的学生，马上就要踏入社会了就想把我的实习、工作、学习的经验经历记录下来。
              该博客主要是会写一些关于java相关的知识，既可以让我自己归纳总结，也可以让大家借鉴一下，要是有
              写的不对的地方大家可以又想提醒我，感谢！
baseurl: "/Shen.github.io"
url: ""
twitter_username: Spt
github_username:  Spt

# Build settings
markdown: kramdown
